package com.company.socialanalytics.report;

import com.company.socialanalytics.dashboard.DashboardService;
import com.company.socialanalytics.dashboard.DashboardSummary;
import com.company.socialanalytics.dashboard.LatestPostView;
import com.company.socialanalytics.dashboard.MetricPoint;
import com.company.socialanalytics.security.CurrentUser;
import java.nio.charset.StandardCharsets;
import java.time.Clock;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

@Service
public class ReportExportService {
    private final DashboardService dashboardService;
    private final Clock clock;

    public ReportExportService(DashboardService dashboardService, Clock clock) {
        this.dashboardService = dashboardService;
        this.clock = clock;
    }

    @Transactional(readOnly = true)
    public byte[] csv(CurrentUser currentUser) {
        DashboardSummary summary = dashboardService.summary(isAdmin(currentUser));
        StringBuilder csv = new StringBuilder();
        csv.append("section,label,value\n");
        appendRow(csv, "summary", "generatedAt", Instant.now(clock).toString());
        appendRow(csv, "summary", "generatedBy", userEmail(currentUser));
        appendRow(csv, "summary", "totalPosts", summary.totalPosts());
        appendRow(csv, "summary", "postsToday", summary.postsToday());
        appendRow(csv, "summary", "postsPerMinute", summary.postsPerMinute());
        appendRow(csv, "summary", "positive", summary.sentiment().positive());
        appendRow(csv, "summary", "neutral", summary.sentiment().neutral());
        appendRow(csv, "summary", "negative", summary.sentiment().negative());
        summary.topHashtags().forEach(point -> appendRow(csv, "topHashtags", point.label(), point.value()));
        summary.topKeywords().forEach(point -> appendRow(csv, "topKeywords", point.label(), point.value()));
        summary.activePlatforms().forEach(point -> appendRow(csv, "activePlatforms", point.label(), point.value()));
        summary.topUsers().forEach(point -> appendRow(csv, "topUsers", point.label(), point.value()));
        csv.append("\nexternalId,platform,author,sentiment,language,publishedAt,content\n");
        for (LatestPostView post : summary.latestPosts()) {
            appendCsvFields(csv, List.of(
                    post.externalId(),
                    post.platform().name(),
                    post.authorUsername(),
                    post.sentiment().name(),
                    post.language(),
                    post.publishedAt().toString(),
                    post.content()
            ));
        }
        return csv.toString().getBytes(StandardCharsets.UTF_8);
    }

    @Transactional(readOnly = true)
    public byte[] pdf(CurrentUser currentUser) {
        DashboardSummary summary = dashboardService.summary(isAdmin(currentUser));
        List<String> lines = new ArrayList<>();
        lines.add("Social Analytics Report");
        lines.add("Generated: " + Instant.now(clock));
        lines.add("Generated by: " + userEmail(currentUser));
        lines.add("Total posts: " + summary.totalPosts());
        lines.add("Posts today: " + summary.postsToday());
        lines.add("Posts per minute: " + summary.postsPerMinute());
        lines.add("Sentiment: positive " + summary.sentiment().positive()
                + ", neutral " + summary.sentiment().neutral()
                + ", negative " + summary.sentiment().negative());
        lines.add("Top hashtags: " + metricLabels(summary.topHashtags()));
        lines.add("Top keywords: " + metricLabels(summary.topKeywords()));
        lines.add("Active platforms: " + metricLabels(summary.activePlatforms()));
        lines.add("Most active users: " + metricLabels(summary.topUsers()));
        lines.add("Latest posts:");
        summary.latestPosts().stream()
                .limit(8)
                .map(post -> post.platform() + " @" + post.authorUsername() + " "
                        + post.sentiment() + " - " + post.content())
                .map(line -> line.length() > 92 ? line.substring(0, 89) + "..." : line)
                .forEach(lines::add);
        return buildPdf(lines);
    }

    private boolean isAdmin(CurrentUser currentUser) {
        return currentUser != null && currentUser.authorities().contains("ROLE_ADMIN");
    }

    private String userEmail(CurrentUser currentUser) {
        return currentUser == null ? "unknown" : currentUser.email();
    }

    private String metricLabels(List<MetricPoint> points) {
        if (points.isEmpty()) {
            return "none";
        }
        return points.stream()
                .limit(6)
                .map(point -> point.label() + " (" + point.value() + ")")
                .reduce((left, right) -> left + ", " + right)
                .orElse("none");
    }

    private void appendRow(StringBuilder csv, String section, String label, Object value) {
        appendCsvFields(csv, List.of(section, label, String.valueOf(value)));
    }

    private void appendCsvFields(StringBuilder csv, List<String> fields) {
        for (int index = 0; index < fields.size(); index += 1) {
            if (index > 0) {
                csv.append(',');
            }
            csv.append('"').append(csvSafe(fields.get(index)).replace("\"", "\"\"")).append('"');
        }
        csv.append('\n');
    }

    private String csvSafe(String value) {
        if (value.isBlank()) {
            return value;
        }
        char first = value.charAt(0);
        if (first == '=' || first == '+' || first == '-' || first == '@') {
            return "'" + value;
        }
        return value;
    }

    private byte[] buildPdf(List<String> lines) {
        StringBuilder content = new StringBuilder();
        content.append("BT /F1 12 Tf 50 742 Td 16 TL\n");
        for (String line : lines) {
            content.append('(').append(escapePdfText(ascii(line))).append(") Tj T*\n");
        }
        content.append("ET\n");

        List<String> objects = List.of(
                "<< /Type /Catalog /Pages 2 0 R >>",
                "<< /Type /Pages /Kids [3 0 R] /Count 1 >>",
                "<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 5 0 R >> >> /Contents 4 0 R >>",
                "<< /Length " + content.toString().getBytes(StandardCharsets.US_ASCII).length + " >>\nstream\n" + content + "endstream",
                "<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>"
        );
        StringBuilder pdf = new StringBuilder("%PDF-1.4\n");
        List<Integer> offsets = new ArrayList<>();
        for (int index = 0; index < objects.size(); index += 1) {
            offsets.add(pdf.toString().getBytes(StandardCharsets.US_ASCII).length);
            pdf.append(index + 1).append(" 0 obj\n")
                    .append(objects.get(index)).append("\nendobj\n");
        }
        int xrefOffset = pdf.toString().getBytes(StandardCharsets.US_ASCII).length;
        pdf.append("xref\n0 ").append(objects.size() + 1).append("\n");
        pdf.append("0000000000 65535 f \n");
        for (Integer offset : offsets) {
            pdf.append(String.format("%010d 00000 n \n", offset));
        }
        pdf.append("trailer << /Size ").append(objects.size() + 1).append(" /Root 1 0 R >>\n");
        pdf.append("startxref\n").append(xrefOffset).append("\n%%EOF\n");
        return pdf.toString().getBytes(StandardCharsets.US_ASCII);
    }

    private String escapePdfText(String text) {
        return text.replace("\\", "\\\\")
                .replace("(", "\\(")
                .replace(")", "\\)");
    }

    private String ascii(String value) {
        return value.replaceAll("[^\\x20-\\x7E]", "?");
    }
}
